name: PyKale_tutorials
channels:
- rusty1s
- pytorch
- conda-forge
- defaults
dependencies:
- cpuonly
- pip
- python==3.7
- pytorch
- pytorch-geometric
- rdkit
- torchaudio
- torchvision
- pip:
  - .[extras]
