# This workflow will automatically add an issue or pull request to the default project.
# The project needs to be updated when we move to a new default project.
# https://github.com/actions/add-to-project
# Follow the following link to create the encrypted secret key
# https://docs.github.com/en/actions/security-guides/encrypted-secrets

name: assign-project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

jobs:
  add-issue-to-project:
    name: Add issue to project
    if: github.event_name == 'issues' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/pykale/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}



  add-pull-request-to-project:
    name: Add pull request to project
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/pykale/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
