# This workflow will install Python dependencies, run tests, and report the coverage with a variety of Python versions and OSs
# For more information see: https://github.com/actions/stale

name: Mark stale issues and pull requests

on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '0 0 * * *' # every midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v4.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          days-before-issue-close: 7
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-issue-message: 'This issue has been automatically marked as stale due to lack of activity. It will be closed if no further activity occurs. Thank you'
          close-issue-message: 'This issue is closed due to lack of activity. Feel free to reopen it if you still have questions.'
          stale-pr-message: 'This pull request has been automatically marked as stale due to lack of activity. It will be closed if no further activity occurs. Thank you'
          close-pr-message: 'This pull request is closed due to lack of activity.'
          stale-issue-label: 'stale-issue'
          exempt-issue-labels: 'bug, enhancement, new feature'
